# github_username|display_name|email|private_signing_key|public_signing_key
DiegoS284|DiegoS284|diego64g284@gmail.com|$HOME/.ssh/nexa_DiegoS284_signing|$HOME/.ssh/nexa_DiegoS284_signing.pub
GerardRojasMancilla|GerardRojasMancilla|U202413142@upc.edu.pe|$HOME/.ssh/nexa_GerardRojasMancilla_signing|$HOME/.ssh/nexa_GerardRojasMancilla_signing.pub
R0obxdnt|R0obxdnt|grtdls525gino1@gmail.com|$HOME/.ssh/nexa_R0obxdnt_signing|$HOME/.ssh/nexa_R0obxdnt_signing.pub
spinedo214|spinedo214|sebastianpinedo214@gmail.com|$HOME/.ssh/nexa_spinedo214_signing|$HOME/.ssh/nexa_spinedo214_signing.pub
JoaquinBV511|JoaquinBV511|joaquinverdebueno@gmail.com|$HOME/.ssh/nexa_JoaquinBV511_signing|$HOME/.ssh/nexa_JoaquinBV511_signing.pub
